edition = "2021"
version = "Two"
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = true
imports_layout = "Vertical"
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
use_small_heuristics = "Default"
merge_derives = true
use_escape = "Inner"
merge_features = true
trailing_comma = "Always"
edition_guide = false
hint = true
